package com.cdac.statewide.hiscommon.service.config;

public interface EssentialCommonDaoConfig {

    String PROCEDURE_GET_COUNTRY_COMBO = "PKG_GBL_VIEW.PROC_GBLT_COUNTRY_MST";
    String PROCEDURE_GET_STATE_COMBO = "PKG_GBL_VIEW.PROC_GBLT_STATE_MST";
    String PROCEDURE_GET_DISTRICT_COMBO = "PKG_GBL_VIEW.PROC_GBLT_DISTRICT_MST";
    String PROCEDURE_GET_DEPT_COMBO = "pkg_reg_view.ProcDeptCombo";
    String PROCEDURE_GET_DOC_COMBO = "PKG_GBL_VIEW.PROC_GBLT_VERIFICATION_DOC_MST";
    String PROCEDURE_GET_GENDER_COMBO = "PKG_GBL_VIEW.PROC_GBLT_GENDER_MST";
    String PROCEDURE_GET_PATIENT_PAYMENT_MODE_COMBO = "pkg_reg_view.proc_sblt_paymentmode_mst";
    String PROCEDURE_GET_PATIENT_CAT_COMBO = "pkg_reg_view.proc_gblt_patient_cat_dtl";
    String PROCEDURE_GET_REF_INSTITUTE_COMBO = "PKG_REG_VIEW.proc_ref_institute_cmb";
    String PROCEDURE_GET_REF_DEPARTMENT_COMBO = "PKG_REG_VIEW.PROC_REFER_DEPARTMENT_LIST";
    String REGISTRATIONDESK_DEFAULT_COUNTRY_CODE = "IND";
    String NEW_REGISTRATION_TARIFF_ID = "1010001";
    String MODULE_ID_REGISTRATION = "11";
    String SUPER_USER_HOSPITAL_CODE = "100";
    String DEPT_TYPE_CLINICAL_VALUE = "1";
}
